apiVersion: v1
kind: ReplicationController
metadata:
 name: nginx-controller
spec:
 replicas: 2
 selector:
   name: nginx
 template:
   metadata:
     labels:
       name: nginx
       app: ngnix
   spec:
     containers:
       - name: nginx
         image: nginx
         ports:
           - containerPort: 80
         volumeMounts:
           - name: mynfssharename
             mountPath: "/usr/share/nginx/html"
     volumes:
     - name: mynfssharename
       persistentVolumeClaim:
         claimName: mynfssharename
