apiVersion: v1
kind: ReplicationController
metadata:
 name: nginx-controller
spec:
 replicas: 2
 selector:
   name: nginx
 template:
   metadata:
     labels:
       name: nginx
   spec:
     containers:
       - name: nginx
         image: nginx
         volumeMounts:
           - name: task-pv-volume
             mountPath: "/usr/share/nginx/html"
         ports:
           - containerPort: 80
  volumes:
  - name: task-pv-volume
    persistentVolumeClaim:
      claimName: task-pv-claim
